trigger:
- main

pool:
  name: Azure Pipelines
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: build

- script: |
    git clone https://github.com/IidaKok/testi
    cd testi
    git checkout gh-pages
    cp -R ../$(Build.ArtifactStagingDirectory)/* ./
    git add .
    git commit -m 'Update gh-pages'
    git push origin gh-pages
  displayName: 'Deploy to gh-pages'
